server:
  port: 8083
spring:
  application:
    name: notification-service
  config:
    activate:
      on-profile: local, dev, local
    import:
      - "optional:configserver:http://config-service:8888"
      - "optional:configserver:http://localhost:8888"
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"